import { expect, test } from '@playwright/test'

test('moves from a blocked profile to an explicitly confirmed fixture application', async ({ page }) => {
  await page.goto('/search')
  await expect(page.getByRole('heading', { name: 'Поиск пока недоступен' })).toBeVisible()
  await page.getByRole('link', { name: 'Открыть профиль' }).click()
  await expect(page.getByText('Профиль не готов')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Настроить поиск' })).toHaveCount(0)

  await page.getByRole('listitem', { name: 'TypeScript' }).getByRole('button', { name: 'Подтвердить' }).click()
  await expect(page.getByText('Профиль готов — можно настроить поиск')).toBeVisible()
  await page.getByRole('link', { name: 'Сервисы', exact: true }).click()
  const source = page.getByRole('region', { name: 'Example Board' })
  await expect(source.getByText('Согласие на поиск: не предоставлено')).toBeVisible()
  await source.getByRole('button', { name: 'Подключить' }).click()
  await expect(source.getByText('Согласие на поиск: предоставлено')).toBeVisible()

  await page.getByRole('link', { name: 'Поиск', exact: true }).click()
  await page.getByRole('textbox', { name: 'Должности и синонимы' }).fill('Frontend Developer')
  await page.getByRole('checkbox', { name: 'Example Board' }).check()
  await page.getByRole('checkbox', { name: 'Удалённая работа' }).check()
  await page.getByRole('combobox', { name: 'Режим обработки' }).selectOption('recommendations')
  await page.getByRole('button', { name: 'Сохранить профиль' }).click()
  const search = page.getByRole('region', { name: 'Frontend Developer' })
  await expect(search.getByText('Состояние: поиск не запущен')).toBeVisible()
  await search.getByRole('button', { name: 'Запустить поиск' }).click()
  await expect(search.getByText('Состояние: поиск активен')).toBeVisible()

  await page.getByRole('link', { name: 'Вакансии', exact: true }).click()
  await page.getByRole('article', { name: 'Frontend Developer' }).getByRole('link', { name: 'Frontend Developer' }).click()
  await expect(page.getByRole('heading', { name: 'Описание вакансии — текст источника' })).toBeVisible()
  await page.getByRole('link', { name: 'Подготовить отклик' }).click()
  await expect(page.getByRole('heading', { name: /Отклик: Frontend Developer/ })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Использованные факты' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Предупреждения' })).toBeVisible()
  const send = page.getByRole('button', { name: 'Подтвердить и отправить' })
  await expect(send).toBeDisabled()
  await page.getByRole('button', { name: 'Подтвердить содержание' }).click()
  await expect(send).toBeEnabled()
  await send.click()
  await expect(page.getByRole('status')).toContainText('Отклик отправлен в демонстрационном режиме')
  await expect(send).toHaveCount(0)
})

test('main navigation is keyboard reachable and focus is visible', async ({ page }) => {
  await page.goto('/profile')
  await page.keyboard.press('Tab')
  const skip = page.getByRole('link', { name: 'Перейти к содержимому' })
  await expect(skip).toBeFocused()
  await expect(skip).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page.locator('main')).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  const settings = page.getByRole('link', { name: 'Настройки' })
  await expect(settings).toBeFocused()
  const outline = await settings.evaluate((element) => getComputedStyle(element).outlineStyle)
  expect(outline).not.toBe('none')
})
